baseURL = 'https://open-tour-2024.netlify.app/'
languageCode = 'en-us'
title = 'Red Hat Open Tour 2024 - Lab "Crazy Train"'

theme = 'hugo-theme-learn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "red"
openshift_domain = "crazy-train.sandbox1730.opentlc.com"
minioPass = "minio123"
minioEndpoint = "https://minio-s3-minio.apps.crazy-train.sandbox1730.opentlc.com"
minioConsole = "https://minio-console-minio.apps.crazy-train.sandbox1730.opentlc.com"
ocpConsole = "https://console-openshift-console.apps.crazy-train.sandbox1730.opentlc.com/"
ocpApi = "https://api.crazy-train.sandbox1730.opentlc.com:6443"
gitRepoName = "workshop-model-training"
gitAIRepoUrl = "https://github.com/Demo-AI-Edge-Crazy-Train/workshop-model-training"
baseModelBucket = "model-registry"
newModelName = "new"
newModelServerName = "Traffic Sign Detection"
newModelDataConnection = "pipelines"
newModelPath = "models/model.onnx"
newModelServerSize = "Small"

# Anglais est la langue par défaut
defaultContentLanguage = "fr"
# Force d'avoir /en/ma-page et /fr/ma-page routes, même avec la langue par défaut.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "Mission Impossible - Help Tom Cruise leverage OpenShift AI to stop the crazy train before it’s too late !"
weight = 1
languageName = "English"

[Languages.fr]
title = "Mission Impossible - Aidez Tom Cruise à tirer parti d'OpenShift AI pour arrêter le train fou avant qu'il ne soit trop tard !"
weight = 2
languageName = "Français"
